USE [BookingEventDB]
GO

/****** Object:  Table [dbo].[Events]    Script Date: 10/19/2017 3:36:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Events](
	[AggregateRootId] [UNIQUEIDENTIFIER] NOT NULL,
	[Version] [INT] NOT NULL,
	[EventName] [NVARCHAR](MAX) NOT NULL,
	[Content] [NVARCHAR](MAX) NOT NULL,
	[OccurredOn] [DATETIME2](7) NOT NULL,
	[AssemblyName] [NVARCHAR](MAX) NOT NULL,
 CONSTRAINT [PK_Events_1] PRIMARY KEY CLUSTERED 
(
	[AggregateRootId] ASC,
	[Version] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO